### ISSUE TITLE
Search for program: Is a directory,

### ISSUE THREAD

**Issue by filip-lovich-kubra** [fwcd/kotlin-language-server#472]
I really don't have much here sorry. Everything works but when I try to use the "Run" or "Debug" lens, nothing happens, just the below message. I checked all buffers (kotlion-ls, lsp-log) but can't find any other error message.

<img width="1132" alt="image" src="https://github.com/fwcd/kotlin-language-server/assets/134314435/07c2a84d-23e0-482d-afb0-e680deabb046">

**Comment by themkat** [comment]
This is not really language server related, but Emacs configuration related. Have you set `lsp-kotlin-debug-adapter-path` to the path to the debug adapter executable? No automatic downloading is done for the debug adapter in lsp-mode (or dap-mode) to my knowledge, so you will have download it yourself and point the variable to the executable path. (not the directory of the executable, but the executable itself). 

(yes, I know. The debug adapter variables should probably have been dap-mode variables instead. The only reason for keeping it in lsp-mode was because they were already present early on. Probably due to the person making the initial config using the VSCode properties verbatim.... 😒 )
