### ISSUE TITLE
[Question] Project doesn't seem to find Kotlin runtime

### ISSUE THREAD

**Issue by BoykoAlex** [fwcd/kotlin-language-server#58]
I have the following errors in my Kotlin class:
![screen shot 2018-10-02 at 18 34 40](https://user-images.githubusercontent.com/6433390/46380925-3efadf00-c672-11e8-84d5-5c8a40a8a7f9.png)

I have installed Kotlin via `brew install kotlin`... what am I missing? Is there a preference setting in VSCode?

Another error:
![screen shot 2018-10-02 at 18 39 45](https://user-images.githubusercontent.com/6433390/46381035-98fba480-c672-11e8-9e06-d98f7d1e3e09.png)

Any advice?

**Comment by fwcd** [comment]
@BoykoAlex Do you use Maven or Gradle? This issue seems to be related to #56 and #51.

You could check whether https://github.com/fwcd/KotlinQuickStart (a sample project that uses Gradle) works correctly and look for stack traces in the output log:

![Screenshot](https://user-images.githubusercontent.com/30873659/45545346-4882eb00-b81a-11e8-96b3-ff440ab4b29d.png)

**Comment by fwcd** [comment]
The 'unresolved reference' error should be fixed by #154 and the JVM target can now be configured in the Kotlin extension settings.
